# .cirrus.yml - Cirrus CI configuration for FreeBSD JRE build

freebsd_jre_build_task:
  name: "Build Static JRE on FreeBSD"
  
  # Use FreeBSD 13.4 as specified
  freebsd_instance:
    image_family: freebsd-13-4
    cpu: 8  # Use more CPUs for faster build
    memory: 16G  # OpenJDK build needs significant memory
  
  # Set timeout - OpenJDK builds can take a long time
  timeout_in: 120m
  
  # Environment variables
  environment:
    OPENJDK_VERSION: "17"  # Change to desired version (8, 11, 17, 21)
    CIRRUS_SHELL: /bin/sh
    ASSUME_ALWAYS_YES: yes  # Auto-answer yes to pkg prompts
  
  # Cache dependencies to speed up subsequent builds
  pkg_cache:
    folder: /var/cache/pkg
    fingerprint_script: echo $FREEBSD_VERSION
  
  # Install script
  install_script: |
    # Fix package repository first
    chmod +x pkg-fix.sh
    ./pkg-fix.sh
    
    # Make build script executable
    chmod +x build-static-jre.sh
    
    # Run the build script
    ./build-static-jre.sh
  
  # Verify script
  verify_script: |
    # Test the built JRE
    if [ -f "openjdk-${OPENJDK_VERSION}-jre-freebsd-$(uname -m)-static.tar.gz" ]; then
      echo "Build artifact created successfully"
      ls -lh *.tar.gz
      
      # Extract and test
      mkdir -p test-jre
      tar -xzf openjdk-${OPENJDK_VERSION}-jre-freebsd-$(uname -m)-static.tar.gz -C test-jre
      
      # Test java execution
      test-jre/bin/java -version
      
      # Show dependencies
      echo "Dependencies check:"
      ldd test-jre/bin/java || echo "Static binary - no dynamic dependencies"
      
      # Show size
      echo "Archive size: $(du -h *.tar.gz | cut -f1)"
    else
      echo "Build failed - no artifact found"
      exit 1
    fi
  
  # Upload artifacts
  artifacts:
    path: "*.tar.gz"
    type: application/gzip
  
  # Optional: Upload logs on failure
  on_failure:
    logs_artifacts:
      path: "/tmp/openjdk-build/**/*.log"
